# Generated by Django 2.1.4 on 2019-04-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='partnersId')),
                ('name', models.CharField(max_length=512, verbose_name='partnersName')),
                ('cusc_code', models.CharField(max_length=128, verbose_name='cuscCode')),
                ('legal_person', models.CharField(max_length=128, verbose_name='legalPerson')),
                ('phone_zone', models.CharField(max_length=8, verbose_name='phoneZone')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=64, null=True, verbose_name='mobile')),
                ('email', models.CharField(max_length=128, verbose_name='email')),
                ('address', models.CharField(max_length=512, verbose_name='address')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='postalCode')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='createTime')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='modifyTime')),
                ('city', models.ForeignKey(db_column='city', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='area.CityArea', verbose_name='city')),
                ('country', models.ForeignKey(db_column='country', on_delete=django.db.models.deletion.CASCADE, related_name='country', to='area.CountryArea', verbose_name='country')),
                ('province', models.ForeignKey(db_column='province', on_delete=django.db.models.deletion.CASCADE, related_name='province', to='area.ProvinceArea', verbose_name='province')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('zone', models.ForeignKey(db_column='zone', on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='area.ZoneArea', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'partners',
                'verbose_name_plural': 'partners',
                'ordering': ['uid'],
            },
        ),
    ]
