# Generated by Django 2.1.4 on 2019-04-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='userProfileId')),
                ('alias', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='alias')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('1000', 'male'), ('2000', 'female'), ('3000', 'secretGender')], default='3000', max_length=4, verbose_name='gender')),
                ('nation', models.CharField(blank=True, help_text='helpTextNation', max_length=32, null=True, verbose_name='nation')),
                ('degrees', models.CharField(blank=True, choices=[('Bachelor', (('1000', 'Bachelor Degree'), ('1001', 'Bachelor Degree of Engineering'), ('1002', 'Bachelor Degree of Science'), ('1003', 'Bachelor Degree of Art'), ('1004', 'Bachelor of Education'), ('1005', 'Bachelor of Business Adm'))), ('Master', (('2000', 'Master Eegree'), ('2001', 'Master of Science'), ('2002', 'Master of Engineering'), ('2003', 'Master of Business Administration'))), ('Doctor', (('3000', 'Doctor Degree'), ('3001', 'Doctor of Philosophy')))], help_text='helpTextDegrees', max_length=15, null=True, verbose_name='degrees')),
                ('id_number', models.CharField(blank=True, help_text='helpTextIdNumber', max_length=32, null=True, verbose_name='idNumber')),
                ('phone_zone', models.CharField(blank=True, max_length=8, null=True, verbose_name='phoneZone')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, verbose_name='mobile')),
                ('address', models.CharField(blank=True, help_text='address', max_length=512, null=True, verbose_name='address')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to='users/images/headpicture/%Y/%m', verbose_name='Avatar')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='createTime')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='modifyTime')),
                ('status', models.IntegerField(choices=[('1000', 'activeStatus'), ('1001', 'disableStatus'), ('1002', 'deleteStatus')], default=1000, editable=False)),
                ('open_id_wechat', models.CharField(blank=True, max_length=64, null=True, verbose_name='openIdWechat')),
                ('union_id_wechat', models.CharField(blank=True, max_length=64, null=True, verbose_name='unionIdWechat')),
                ('open_id_ali', models.CharField(blank=True, max_length=64, null=True, verbose_name='openIdAli')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_user', to='area.CityArea', verbose_name='city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_user', to='area.CountryArea', verbose_name='country')),
                ('partners_user', models.ManyToManyField(blank=True, null=True, to='partners.Partners', verbose_name='partners')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_user', to='area.ProvinceArea', verbose_name='province')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_user', to='area.ZoneArea', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'userProfile',
                'verbose_name_plural': 'userProfile',
                'ordering': ['uid'],
            },
        ),
    ]
